spring:
  datasource:
    username: sa
    password: password1234!
    url: jdbc:sqlserver://localhost:3306;databaseName=demo-db;multiSubnetFailover=true;ApplicationIntent=ReadWrite;sendStringParametersAsUnicode=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    maximumPoolSize: 5
    poolName: demo-ds
    connectionInitSql: SELECT GETDATE()
    connectionTestQuery: SELECT GETDATE()
  messages:
    encoding: UTF-8
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8096
  servlet:
    context-path: /demo-service
    session:
      timeout: 30000
  ssl:
    enabled: false
logging:
  level:
    org:
      springframework: INFO
      hibernate: ERROR